'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DMSDownloader04

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txt_mblno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mblno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_sblno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sblno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_hblno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hblno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_username As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dbginfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbginfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''token control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents token As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''G1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents G1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnD1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnD2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnD2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnD3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnD3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnD4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnD4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_dmsuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_dmsuser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''debugmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents debugmsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''G2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents G2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ft1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ft1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''supp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supp1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''agt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agt1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updr1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ft2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ft2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''agt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agt2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updr2 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''sts2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sts2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ft3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ft3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''agt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agt3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updr3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updr3 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''sts3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sts3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ft4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ft4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''agt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agt4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updr4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updr4 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''sts4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sts4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ft5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ft5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''agt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents agt5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updr5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updr5 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''sts5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sts5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bunUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bunUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bunRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bunRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''postjs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postjs As Global.System.Web.UI.WebControls.Literal
End Class
