'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'
'     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
'     程式碼，變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' SuccessMessagePlaceHolder 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' setPassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' 密碼控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' confirmPassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' changePasswordHolder 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' changePasswordUserName 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents changePasswordUserName As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' CurrentPasswordLabel 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' CurrentPassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' NewPasswordLabel 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' NewPassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    ''' <summary>
    ''' ConfirmNewPasswordLabel 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' ConfirmNewPassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
    
End Class
